Melbourne_suburbs = ('ABBOTSFORD','ABERFELDIE','AIRPORT WEST','ALBANVALE','ALBERT PARK','ALBION','ALPHINGTON','ALTONA','ALTONA MEADOWS','ALTONA NORTH','ARDEER','ARMADALE','ASCOT VALE','ASHBURTON','ASHWOOD','ASPENDALE','ASPENDALE GARDENS','ATTWOOD','AVONDALE HEIGHTS','BACCHUS MARSH','BALACLAVA','BALWYN','BALWYN NORTH','BAYSWATER','BAYSWATER NORTH','BEACONSFIELD','BEACONSFIELD UPPER','BEAUMARIS','BELLFIELD','BENTLEIGH','BENTLEIGH EAST','BERWICK','BLACK ROCK','BLACKBURN','BLACKBURN NORTH','BLACKBURN SOUTH','BONBEACH','BORONIA','BOTANIC RIDGE','BOX HILL','BRAYBROOK','BRIAR HILL','BRIGHTON','BRIGHTON EAST','BROADMEADOWS','BROOKFIELD','BROOKLYN','BRUNSWICK','BRUNSWICK EAST','BRUNSWICK WEST','BULLEEN','BULLENGAROOK','BUNDOORA','BURNLEY','BURNSIDE','BURNSIDE HEIGHTS','BURWOOD','BURWOOD EAST','CAIRNLEA','CAMBERWELL','CAMPBELLFIELD','CANTERBURY','CARLTON','CARLTON NORTH','CARNEGIE','CAROLINE SPRINGS','CARRUM','CARRUM DOWNS','CAULFIELD','CAULFIELD EAST','CAULFIELD NORTH','CAULFIELD SOUTH','CHADSTONE','CHELSEA','CHELSEA HEIGHTS','CHELTENHAM','CHIRNSIDE PARK','CLARINDA','CLAYTON','CLAYTON SOUTH','CLIFTON HILL','COBURG','COBURG NORTH','COLLINGWOOD','COOLAROO','CRAIGIEBURN','CRANBOURNE','CRANBOURNE NORTH','CREMORNE','CROYDON','CROYDON HILLS','CROYDON NORTH','CROYDON SOUTH','DALLAS','DANDENONG','DANDENONG NORTH','DEEPDENE','DEER PARK','DELAHEY','DERRIMUT','DIAMOND CREEK','DIGGERS REST','DINGLEY VILLAGE','DONCASTER','DONCASTER EAST','DONVALE','DOREEN','DOVETON','EAGLEMONT','EAST MELBOURNE','EDITHVALE','ELSTERNWICK','ELTHAM','ELTHAM NORTH','ELWOOD','EMERALD','ENDEAVOUR HILLS','EPPING','ESSENDON','ESSENDON NORTH','ESSENDON WEST','FAIRFIELD','FAWKNER','FERNTREE GULLY','FITZROY','FITZROY NORTH','FLEMINGTON','FOOTSCRAY','FOREST HILL','FRANKSTON','FRANKSTON NORTH','FRANKSTON SOUTH','GARDENVALE','GISBORNE','GISBORNE SOUTH','GLADSTONE PARK','GLEN HUNTLY','GLEN IRIS','GLEN WAVERLEY','GLENROY','GOWANBRAE','GREENSBOROUGH','GREENVALE','HADFIELD','HALLAM','HAMPTON','HAMPTON EAST','HAMPTON PARK','HAWTHORN','HAWTHORN EAST','HEALESVILLE','HEATHMONT','HEIDELBERG','HEIDELBERG HEIGHTS','HEIDELBERG WEST','HIGHETT','HILLSIDE','HOPPERS CROSSING','HUGHESDALE','HUNTINGDALE','HURSTBRIDGE','IVANHOE','IVANHOE EAST','JACANA','KEALBA','KEILOR','KEILOR DOWNS','KEILOR EAST','KEILOR LODGE','KEILOR PARK','KENSINGTON','KEW','KEW EAST','KEYSBOROUGH','KILSYTH','KINGS PARK','KINGSBURY','KINGSVILLE','KNOXFIELD','KOOYONG','KURUNJANG','LALOR','LANGWARRIN','LOWER PLENTY','LYSTERFIELD','MAIDSTONE','MALVERN','MALVERN EAST','MARIBYRNONG','MCKINNON','MEADOW HEIGHTS','MELBOURNE','MELTON','MELTON SOUTH','MELTON WEST','MENTONE','MERNDA','MICKLEHAM','MIDDLE PARK','MILL PARK','MITCHAM','MONT ALBERT','MONTMORENCY','MONTROSE','MOONEE PONDS','MOORABBIN','MOOROOLBARK','MORDIALLOC','MOUNT EVELYN','MOUNT WAVERLEY','MULGRAVE','MURRUMBEENA','NARRE WARREN','NEWPORT','NIDDRIE','NOBLE PARK','NORTH MELBOURNE','NORTH WARRANDYTE','NORTHCOTE','NOTTING HILL','NUNAWADING','OAK PARK','OAKLEIGH','OAKLEIGH EAST','OAKLEIGH SOUTH','OFFICER','ORMOND','PAKENHAM','PARKDALE','PARKVILLE','PASCOE VALE','PATTERSON LAKES','PLUMPTON','POINT COOK','PORT MELBOURNE','PRAHRAN','PRESTON','PRINCES HILL','RESEARCH','RESERVOIR','RICHMOND','RIDDELLS CREEK','RINGWOOD','RINGWOOD EAST','RINGWOOD NORTH','RIPPONLEA','ROSANNA','ROWVILLE','ROXBURGH PARK','SANDHURST','SANDRINGHAM','SCORESBY','SEABROOK','SEAFORD','SEAHOLME','SEDDON','SKYE','SOUTH KINGSVILLE','SOUTH MELBOURNE','SOUTH MORANG','SOUTH YARRA','SOUTHBANK','SPOTSWOOD','SPRINGVALE','SPRINGVALE SOUTH','ST ALBANS','ST HELENA','ST KILDA','STRATHMORE','STRATHMORE HEIGHTS','SUNBURY','SUNSHINE','SUNSHINE NORTH','SUNSHINE WEST','SURREY HILLS','SYDENHAM','TARNEIT','TAYLORS HILL','TAYLORS LAKES','TEMPLESTOWE','TEMPLESTOWE LOWER','THE BASIN','THOMASTOWN','THORNBURY','TOORAK','TRAVANCORE','TRUGANINA','TULLAMARINE','UPWEY','VERMONT','VERMONT SOUTH','VIEWBANK','WALLAN','WANTIRNA','WANTIRNA SOUTH','WARRANDYTE','WATERWAYS','WATSONIA','WATSONIA NORTH','WATTLE GLEN','WERRIBEE','WEST FOOTSCRAY','WEST MELBOURNE','WESTMEADOWS','WHEELERS HILL','WHITTLESEA','WILLIAMS LANDING','WILLIAMSTOWN','WILLIAMSTOWN NORTH','WINDSOR','WOLLERT','WYNDHAM VALE','YALLAMBIE','YARRA GLEN','YARRAVILLE')
Sydney_suburbs =(
'Abbotsbury',
'Abbotsford',
'Acacia Gardens',
'Agnes Banks',
'Airds',
'Alexandria',
'Alfords Point',
'Alison',
'Allambie Heights',
'Allawah',
'Ambarvale',
'Annandale',
'Annangrove',
'Appin',
'Arcadia',
'Arncliffe',
'Arndell Park',
'Artarmon',
'Ashbury',
'Ashcroft',
'Ashfield',
'Asquith',
'Auburn',
'Austral',
'Avalon Beach',
'Avoca Beach',
'Badgerys Creek',
'Balgowlah',
'Balgowlah Heights',
'Balmain',
'Balmain East',
'Bangor',
'Banksia',
'Banksmeadow',
'Bankstown',
'Bankstown Aerodrome',
'Bar Point',
'Barangaroo',
'Barden Ridge',
'Bardia',
'Bardwell Park',
'Bardwell Valley',
'Bass Hill',
'Bateau Bay',
'Baulkham Hills',
'Bayview',
'Beacon Hill',
'Beaconsfield',
'Beaumont Hills',
'Beecroft',
'Belfield',
'Belimbla Park',
'Bell',
'Bella Vista',
'Bellevue Hill',
'Belmore',
'Belrose',
'Bensville',
'Berala',
'Berambing',
'Berkeley Vale',
'Berkshire Park',
'Berowra',
'Berowra Creek',
'Berowra Heights',
'Berowra Waters',
'Berrilee',
'Beverley Park',
'Beverly Hills',
'Bexley',
'Bexley North',
'Bidwill',
'Bilgola Beach',
'Bilgola Plateau',
'Bilpin',
'Birchgrove',
'Birrong',
'Blackett',
'Blackheath',
'Blacktown',
'Blackwall',
'Blair Athol',
'Blairmount',
'Blakehurst',
'Blaxland',
'Blaxlands Ridge',
'Bligh Park',
'Blue Bay',
'Blue Haven',
'Blue Mountains National Park',
'Bondi',
'Bondi Beach',
'Bondi Junction',
'Bonnet Bay',
'Bonnyrigg',
'Bonnyrigg Heights',
'Booker Bay',
'Bossley Park',
'Botany',
'Bouddi',
'Bow Bowing',
'Bowen Mountain',
'Box Head',
'Box Hill',
'Bradbury',
'Breakfast Point',
'Brighton-le-Sands',
'Bringelly',
'Bronte',
'Brooklyn',
'Brookvale',
'Brownlow Hill',
'Budgewoi',
'Budgewoi Peninsula',
'Buff Point',
'Bullaburra',
'Bundeena',
'Bungarribee',
'Burraneer',
'Burwood',
'Burwood Heights',
'Busby',
'Bushells Ridge',
'Buxton',
'Cabarita',
'Cabramatta',
'Cabramatta West',
'Caddens',
'Calga',
'Cambridge Gardens',
'Cambridge Park',
'Camden',
'Camden Park',
'Camden South',
'Camellia',
'Cammeray',
'Campbelltown',
'Camperdown',
'Campsie',
'Canada Bay',
'Canley Heights',
'Canley Vale',
'Canoelands',
'Canterbury',
'Canton Beach',
'Caringbah',
'Caringbah South',
'Carlingford',
'Carlton',
'Carnes Hill',
'Carramar',
'Carss Park',
'Cartwright',
'Castle Cove',
'Castle Hill',
'Castlecrag',
'Castlereagh',
'Casula',
'Catherine Field',
'Cattai',
'Cawdor',
'Cecil Hills',
'Cecil Park',
'Cedar Brush Creek',
'Centennial Park',
'Central Colo',
'Central Macdonald',
'Central Mangrove',
'Chain Valley Bay',
'Charmhaven',
'Chatswood',
'Chatswood West',
'Cheero Point',
'Cheltenham',
'Cherrybrook',
'Chester Hill',
'Chifley',
'Chippendale',
'Chipping Norton',
'Chiswick',
'Chittaway Bay',
'Chittaway Point',
'Chullora',
'Church Point',
'Claremont Meadows',
'Clarendon',
'Clareville',
'Claymore',
'Clemton Park',
'Clontarf',
'Clovelly',
'Clyde',
'Coasters Retreat',
'Cobbitty',
'Cogra Bay',
'Colebee',
'Collaroy',
'Collaroy Plateau',
'Colo',
'Colo Heights',
'Colongra',
'Colyton',
'Como',
'Concord',
'Concord West',
'Condell Park',
'Connells Point',
'Constitution Hill',
'Coogee',
'Copacabana',
'Cornwallis',
'Cottage Point',
'Couridjah',
'Cowan',
'Cranebrook',
'Crangan Bay',
'Cremorne',
'Cremorne Point',
'Cromer',
'Cronulla',
'Crows Nest',
'Croydon',
'Croydon Park',
'Cumberland Reach',
'Curl Curl',
'Currans Hill',
'Daceyville',
'Daleys Point',
'Dangar Island',
'Darling Point',
'Darlinghurst',
'Darlington',
'Davidson',
'Davistown',
'Dawes Point',
'Dean Park',
'Dee Why',
'Denham Court',
'Denistone',
'Denistone East',
'Denistone West',
'Dharruk',
'Dolans Bay',
'Dolls Point',
'Doonside',
'Dooralong',
'Double Bay',
'Douglas Park',
'Dover Heights',
'Doyalson',
'Doyalson North',
'Drummoyne',
'Duffys Forest',
'Dulwich Hill',
'Dundas',
'Dundas Valley',
'Dural',
'Durren Durren',
'Eagle Vale',
'Earlwood',
'East Gosford',
'East Hills',
'East Killara',
'East Kurrajong',
'East Lindfield',
'East Ryde',
'Eastern Creek',
'Eastgardens',
'Eastlakes',
'Eastwood',
'Ebenezer',
'Edensor Park',
'Edgecliff',
'Edmondson Park',
'Elanora Heights',
'Elderslie',
'Elizabeth Bay',
'Elizabeth Hills',
'Ellis Lane',
'Elvina Bay',
'Emerton',
'Empire Bay',
'Emu Heights',
'Emu Plains',
'Enfield',
'Engadine',
'Englorie Park',
'Enmore',
'Epping',
'Erina',
'Erina Heights',
'Ermington',
'Erskine Park',
'Erskineville',
'Eschol Park',
'Ettalong Beach',
'Eveleigh',
'Fairfield',
'Fairfield East',
'Fairfield Heights',
'Fairfield West',
'Fairlight',
'Faulconbridge',
'Fernances',
'Fiddletown',
'Five Dock',
'Forest Glen',
'Forest Lodge',
'Forestville',
'Forresters Beach',
'Fountaindale',
'Frazer Park',
'Freemans',
'Freemans Reach',
'Frenchs Forest',
'Freshwater',
'Galston',
'Georges Hall',
'Gilead',
'Girraween',
'Gladesville',
'Glebe',
'Gledswood Hills',
'Glen Alpine',
'Glenbrook',
'Glendenning',
'Glenfield',
'Glenhaven',
'Glenmore',
'Glenmore Park',
'Glenning Valley',
'Glenorie',
'Glenwood',
'Glenworth Valley',
'Glossodia',
'Gordon',
'Gorokan',
'Gosford',
'Granville',
'Grasmere',
'Grays Point',
'Great Mackerel Beach',
'Green Point',
'Green Point',
'Green Valley',
'Greenacre',
'Greendale',
'Greenfield Park',
'Greengrove',
'Greenhills Beach',
'Greenwich',
'Gregory Hills',
'Greystanes',
'Grose Vale',
'Grose Wold',
'Guildford',
'Guildford West',
'Gunderman',
'Gwandalan',
'Gymea',
'Gymea Bay',
'Haberfield',
'Halekulani',
'Halloran',
'Hamlyn Terrace',
'Hammondville',
'Hardys Bay',
'Harrington Park',
'Harris Park',
'Hassall Grove',
'Hawkesbury Heights',
'Haymarket',
'Hazelbrook',
'Heathcote',
'Hebersham',
'Heckenberg',
'Henley',
'Higher Macdonald',
'Hillsdale',
'Hinchinbrook',
'Hobartville',
'Holgate',
'Holroyd',
'Holsworthy',
'Homebush',
'Homebush West',
'Horningsea Park',
'Hornsby',
'Hornsby Heights',
'Horsfield Bay',
'Horsley Park',
'Hoxton Park',
'Hunters Hill',
'Huntingwood',
'Huntleys Cove',
'Huntleys Point',
'Hurlstone Park',
'Hurstville',
'Hurstville Grove',
'Illawong',
'Ingleburn',
'Ingleside',
'Jamisontown',
'Jannali',
'Jilliby',
'Jordan Springs',
'Kanangra',
'Kangaroo Point',
'Kangy Angy',
'Kanwal',
'Kareela',
'Kariong',
'Katoomba',
'Kearns',
'Kellyville',
'Kellyville Ridge',
'Kemps Creek',
'Kensington',
'Kenthurst',
'Kentlyn',
'Kiar',
'Killara',
'Killarney Heights',
'Killarney Vale',
'Killcare',
'Killcare Heights',
'Kincumber',
'Kincumber South',
'Kingfisher Shores',
'Kings Langley',
'Kings Park',
'Kingsford',
'Kingsgrove',
'Kingswood',
'Kirkham',
'Kirrawee',
'Kirribilli',
'Kogarah',
'Kogarah Bay',
'Koolewong',
'Kulnura',
'Ku-Ring-Gai Chase',
'Kurmond',
'Kurnell',
'Kurraba Point',
'Kurrajong',
'Kurrajong Heights',
'Kurrajong Hills',
'Kyeemagh',
'Kyle Bay',
'La Perouse',
'Lake Haven',
'Lake Munmorah',
'Lakemba',
'Lakesland',
'Lalor Park',
'Lane Cove',
'Lane Cove North',
'Lane Cove West',
'Lansdowne',
'Lansvale',
'Lapstone',
'Laughtondale',
'Lavender Bay',
'Lawson',
'Leets Vale',
'Leichhardt',
'Lemon Tree',
'Len Waters Estate',
'Leonay',
'Leppington',
'Lethbridge Park',
'Leumeah',
'Leura',
'Lewisham',
'Liberty Grove',
'Lidcombe',
'Lilli Pilli',
'Lilyfield',
'Linden',
'Lindfield',
'Linley Point',
'Lisarow',
'Little Bay',
'Little Jilliby',
'Little Wobby',
'Liverpool',
'Llandilo',
'Loftus',
'Londonderry',
'Long Jetty',
'Long Point',
'Longueville',
'Lovett Bay',
'Lower Macdonald',
'Lower Mangrove',
'Lower Portland',
'Lucas Heights',
'Luddenham',
'Lugarno',
'Lurnea',
'Macmasters Beach',
'Macquarie Fields',
'Macquarie Links',
'Macquarie Park',
'Magenta',
'Maianbar',
'Malabar',
'Maldon',
'Mangrove Creek',
'Mangrove Mountain',
'Manly',
'Manly Vale',
'Mannering Park',
'Maraylya',
'Marayong',
'Mardi',
'Marlow',
'Maroota',
'Maroubra',
'Marrickville',
'Marsden Park',
'Marsfield',
'Mascot',
'Matcham',
'Matraville',
'Mays Hill',
'McGraths Hill',
'McMahons Point',
'Meadowbank',
'Medlow Bath',
'Megalong Valley',
'Mellong',
'Melrose Park',
'Menai',
'Menangle',
'Menangle Park',
'Merrylands',
'Merrylands West',
'Middle Cove',
'Middle Dural',
'Middleton Grange',
'Miller',
'Millers Point',
'Milperra',
'Milsons Passage',
'Milsons Point',
'Minchinbury',
'Minto',
'Minto Heights',
'Miranda',
'Mogo Creek',
'Mona Vale',
'Monterey',
'Mooney Mooney',
'Mooney Mooney Creek',
'Moore Park',
'Moorebank',
'Morning Bay',
'Mortdale',
'Mortlake',
'Mosman',
'Mount Annan',
'Mount Colah',
'Mount Druitt',
'Mount Elliot',
'Mount Hunter',
'Mount Irvine',
'Mount Kuring-Gai',
'Mount Lewis',
'Mount Pritchard',
'Mount Riverview',
'Mount Tomah',
'Mount Vernon',
'Mount Victoria',
'Mount White',
'Mount Wilson',
'Mountain Lagoon',
'Mowbray Park',
'Mulgoa',
'Mulgrave',
'Narara',
'Narellan',
'Narellan Vale',
'Naremburn',
'Narrabeen',
'Narraweena',
'Narwee',
'Nattai',
'Nelson',
'Neutral Bay',
'Newington',
'Newport',
'Newtown',
'Niagara Park',
'Norah Head',
'Noraville',
'Normanhurst',
'North Avoca',
'North Balgowlah',
'North Bondi',
'North Curl Curl',
'North Epping',
'North Gosford',
'North Manly',
'North Narrabeen',
'North Parramatta',
'North Richmond',
'North Rocks',
'North Ryde',
'North St Marys',
'North Strathfield',
'North Sydney',
'North Turramurra',
'North Wahroonga',
'North Willoughby',
'Northbridge',
'Northmead',
'Northwood',
'Oakdale',
'Oakhurst',
'Oakville',
'Oatlands',
'Oatley',
'Old Guildford',
'Old Toongabbie',
'Oran Park',
'Orangeville',
'Orchard Hills',
'Ourimbah',
'Oxford Falls',
'Oxley Park',
'Oyster Bay',
'Paddington',
'Padstow',
'Padstow Heights',
'Pagewood',
'Palm Beach',
'Palm Grove',
'Palmdale',
'Panania',
'Parklea',
'Parramatta',
'Patonga',
'Peakhurst',
'Peakhurst Heights',
'Pearl Beach',
'Peats Ridge',
'Pemulwuy',
'Pendle Hill',
'Pennant Hills',
'Penrith',
'Penshurst',
'Perrys Crossing',
'Petersham',
'Phegans Bay',
'Phillip Bay',
'Picketts Valley',
'Picnic Point',
'Picton',
'Pitt Town',
'Pitt Town Bottoms',
'Pleasure Point',
'Plumpton',
'Point Clare',
'Point Frederick',
'Point Piper',
'Point Wolstoncroft',
'Port Botany',
'Port Hacking',
'Potts Hill',
'Potts Point',
'Prairiewood',
'Prestons',
'Pretty Beach',
'Prospect',
'Punchbowl',
'Putney',
'Putty',
'Pymble',
'Pyrmont',
'Quakers Hill',
'Queens Park',
'Queenscliff',
'Raby',
'Ramsgate',
'Ramsgate Beach',
'Randwick',
'Ravensdale',
'Razorback',
'Redfern',
'Regents Park',
'Regentville',
'Revesby',
'Revesby Heights',
'Rhodes',
'Richmond',
'Richmond Lowlands',
'Riverstone',
'Riverview',
'Riverwood',
'Rockdale',
'Rocky Point',
'Rodd Point',
'Rookwood',
'Rooty Hill',
'Ropes Crossing',
'Rose Bay',
'Rosebery',
'Rosehill',
'Roselands',
'Rosemeadow',
'Roseville',
'Roseville Chase',
'Rossmore',
'Rouse Hill',
'Royal National Park',
'Rozelle',
'Ruse',
'Rushcutters Bay',
'Russell Lea',
'Rydalmere',
'Ryde',
'Sackville',
'Sackville North',
'Sadleir',
'San Remo',
'Sandringham',
'Sandy Point',
'Sans Souci',
'Saratoga',
'Scheyville',
'Schofields',
'Scotland Island',
'Seaforth',
'Sefton',
'Seven Hills',
'Shalvey',
'Shanes Park',
'Shelly Beach',
'Silverdale',
'Silverwater',
'Singletons Mill',
'Smeaton Grange',
'Smithfield',
'Somersby',
'South Coogee',
'South Granville',
'South Hurstville',
'South Maroota',
'South Penrith',
'South Turramurra',
'South Wentworthville',
'South Windsor',
'Spencer',
'Spring Farm',
'Springfield',
'Springwood',
'St Albans',
'St Andrews',
'St Clair',
'St Helens Park',
'St Huberts Island',
'St Ives',
'St Ives Chase',
'St Johns Park',
'St Leonards',
'St Marys',
'St Peters',
'Stanhope Gardens',
'Stanmore',
'Strathfield',
'Strathfield South',
'Summer Hill',
'Summerland Point',
'Sun Valley',
'Surry Hills',
'Sutherland',
'Sydenham',
'Sydney',
'Sydney Olympic Park',
'Sylvania',
'Sylvania Waters',
'Tacoma',
'Tacoma South',
'Tahmoor',
'Tamarama',
'Taren Point',
'Tascott',
'Telopea',
'Tempe',
'Ten Mile Hollow',
'Tennyson',
'Tennyson Point',
'Terrey Hills',
'Terrigal',
'The Devils Wilderness',
'The Entrance',
'The Entrance North',
'The Oaks',
'The Ponds',
'The Rocks',
'The Slopes',
'Theresa Park',
'Thirlmere',
'Thornleigh',
'Toongabbie',
'Toowoon Bay',
'Toukley',
'Tregear',
'Tuggerah',
'Tuggerawong',
'Tumbi Umbi',
'Turramurra',
'Turrella',
'Ultimo',
'Umina Beach',
'Upper Colo',
'Upper Macdonald',
'Upper Mangrove',
'Valley Heights',
'Varroville',
'Vaucluse',
'Villawood',
'Vineyard',
'Voyager Point',
'Wadalba',
'Wagstaffe',
'Wahroonga',
'Waitara',
'Wakeley',
'Wallacia',
'Wallarah',
'Wamberal',
'Wareemba',
'Warnervale',
'Warragamba',
'Warrawee',
'Warriewood',
'Warrimoo',
'Warwick Farm',
'Watanobbi',
'Waterfall',
'Waterloo',
'Watsons Bay',
'Wattle Grove',
'Waverley',
'Waverton',
'Webbs Creek',
'Wedderburn',
'Wendoree Park',
'Wentworth Falls',
'Wentworth Point',
'Wentworthville',
'Werombi',
'Werrington',
'Werrington County',
'Werrington Downs',
'West Gosford',
'West Hoxton',
'West Pennant Hills',
'West Pymble',
'West Ryde',
'Westleigh',
'Westmead',
'Wetherill Park',
'Whalan',
'Whale Beach',
'Wheeler Heights',
'Wheeny Creek',
'Wilberforce',
'Wiley Park',
'Willmot',
'Willoughby',
'Willoughby East',
'Wilton',
'Windsor',
'Windsor Downs',
'Winmalee',
'Winston Hills',
'Wisemans Ferry',
'Wolli Creek',
'Wollstonecraft',
'Womerah',
'Wondabyne',
'Woodbine',
'Woodcroft',
'Woodford',
'Woodpark',
'Woollahra',
'Woolloomooloo',
'Woolooware',
'Woolwich',
'Woongarrah',
'Woronora',
'Woronora Heights',
'Woy Woy',
'Woy Woy Bay',
'Wrights Creek',
'Wybung',
'Wyoming',
'Wyong',
'Wyong Creek',
'Wyongah',
'Yagoona',
'Yanderra',
'Yarramalong',
'Yarramundi',
'Yarrawarrah',
'Yattalunga',
'Yellow Rock',
'Yennora',
'Yerranderie',
'Yowie Bay',
'Zetland',
)


Brisbane_suburbs = (
'Acacia Ridge',
'Albany Creek',
'Albion',
'Alderley',
'Alexandra Hills',
'Algester',
'Allandale',
'Allenview',
'Amberley',
'Amity',
'Annerley',
'Anstead',
'Anthony',
'Arana Hills',
'Aratula',
'Archerfield',
'Armstrong Creek',
'Ascot',
'Ashgrove',
'Ashwell',
'Aspley',
'Atkinsons Dam',
'Auchenflower',
'Augustine Heights',
'Avoca Vale',
'Bahrs Scrub',
'Bald Hills',
'Balmoral',
'Banks Creek',
'Banksia Beach',
'Bannockburn',
'Banyo',
'Bardon',
'Barellan Point',
'Barney View',
'Basin Pocket',
'Beachmere',
'Beaudesert',
'Beenleigh',
'Belivah',
'Bellara',
'Bellbird Park',
'Bellbowrie',
'Bellmere',
'Bellthorpe',
'Belmont',
'Berrinba',
'Bethania',
'Biarra',
'Biddaddaba',
'Birkdale',
'Birnam',
'Blacksoil',
'Blackstone',
'Blantyre',
'Blenheim',
'Bongaree',
'Boonah',
'Boondall',
'Booroobin',
'Booval',
'Borallon',
'Boronia Heights',
'Bowen Hills',
'Bracalba',
'Bracken Ridge',
'Braemore',
'Brassall',
'Bray Park',
'Brendale',
'Bribie Island North',
'Bridgeman Downs',
'Brighton',
'Brightview',
'Brisbane Airport',
'Brisbane City',
'Bromelton',
'Brookfield',
'Brookwater',
'Browns Plains',
'Bryden',
'Buaraba',
'Buccan',
'Bulimba',
'Bulwer',
'Bunburra',
'Bundamba',
'Bunjurgen',
'Bunya',
'Burbank',
'Burnett Creek',
'Burpengary',
'Burpengary East',
'Caboolture',
'Caboolture South',
'Caboonbah',
'Cainbable',
'Calamvale',
'Calvert',
'Camira',
'Camp Hill',
'Camp Mountain',
'Campbells Pocket',
'Cannon Creek',
'Cannon Hill',
'Capalaba',
'Carbrook',
'Carina',
'Carina Heights',
'Carindale',
'Carneys Creek',
'Carole Park',
'Carseldine',
'Cashmere',
'Cedar Creek',
'Cedar Creek',
'Cedar Grove',
'Cedar Vale',
'Cedarton',
'Chambers Flat',
'Chandler',
'Chapel Hill',
'Charlwood',
'Chelmer',
'Chermside',
'Chermside West',
'Chinghee Creek',
'Christmas Creek',
'Churchable',
'Churchill',
'Chuwar',
'Clarendon',
'Clayfield',
'Clear Mountain',
'Cleveland',
'Clontarf',
'Closeburn',
'Clumber',
'Coal Creek',
'Coalfalls',
'Coleyville',
'Colinton',
'College View',
'Collingwood Park',
'Commissioners Flat',
'Coochiemudlo Island',
'Coochin',
'Cooeeimbardi',
'Coolana',
'Coominya',
'Coopers Plains',
'Coorparoo',
'Corinda',
'Cornubia',
'Coulson',
'Cowan Cowan',
'Cressbrook',
'Crestmead',
'Croftby',
'Crossdale',
'Crowley Vale',
'Cryna',
'Daisy Hill',
'Dakabin',
'Darlington',
'Darra',
'Dayboro',
'Deagon',
'Deception Bay',
'Deebing Heights',
'Delaneys Creek',
'Dinmore',
'Donnybrook',
'Doolandella',
'Draper',
'Drewvale',
'Dugandan',
'Dundas',
'Dunwich',
'Durack',
'Dutton Park',
'Eagle Farm',
'Eagleby',
'East Brisbane',
'East Ipswich',
'Eastern Heights',
'Eatons Hill',
'Ebbw Vale',
'Ebenezer',
'Edens Landing',
'Eight Mile Plains',
'Elimbah',
'Ellen Grove',
'England Creek',
'Enoggera',
'Enoggera Reservoir',
'Esk',
'Eskdale',
'Everton Hills',
'Everton Park',
'Fairfield',
'Fairney View',
'Fassifern',
'Fassifern Valley',
'Fernvale',
'Ferny Grove',
'Ferny Hills',
'Fig Tree Pocket',
'Fitzgibbon',
'Flinders View',
'Forest Hill',
'Forest Lake',
'Forestdale',
'Fortitude Valley',
'Frazerview',
'Frenches Creek',
'Fulham',
'Gailes',
'Gaythorne',
'Geebung',
'Glamorgan Vale',
'Glen Cairn',
'Glen Esk',
'Gleneagle',
'Glenfern',
'Glenore Grove',
'Godwin Beach',
'Goodna',
'Goolman',
'Gordon Park',
'Graceville',
'Grandchester',
'Grange',
'Greenbank',
'Greenslopes',
'Gregors Creek',
'Griffin',
'Gumdale',
'Haigslea',
'Hamilton',
'Harlin',
'Harrisville',
'Hatton Vale',
'Hawthorne',
'Hazeldean',
'Heathwood',
'Hemmant',
'Hendra',
'Heritage Park',
'Herston',
'Highgate Hill',
'Highvale',
'Hillcrest',
'Hillview',
'Holland Park',
'Holland Park West',
'Holmview',
'Hoya',
'Inala',
'Indooroopilly',
'Innisplain',
'Ipswich',
'Ironbark',
'Ivory Creek',
'Jamboree Heights',
'Jeebropilly',
'Jimboomba',
'Jimna',
'Jindalee',
'Jollys Lookout',
'Josephville',
'Joyner',
'Kagaru',
'Kairabah',
'Kalbar',
'Kalinga',
'Kallangur',
'Kangaroo Point',
'Karalee',
'Karana Downs',
'Karawatha',
'Karrabin',
'Karragarra Island',
'Kedron',
'Kelvin Grove',
'Kenmore',
'Kenmore Hills',
'Kensington Grove',
'Kents Lagoon',
'Kents Pocket',
'Kentville',
'Keperra',
'Kerry',
'Kholo',
'Kilcoy',
'King Scrub',
'Kingaham',
'Kingston',
'Kippa-Ring',
'Knapp Creek',
'Kobble Creek',
'Kooralbyn',
'Kooringal',
'Kulgun',
'Kuraby',
'Kurwongbah',
'Laceys Creek',
'Laidley',
'Laidley Creek West',
'Laidley Heights',
'Laidley North',
'Laidley South',
'Lake Clarendon',
'Lake Manchester',
'Lake Wivenhoe',
'Lamb Island',
'Lamington',
'Lanefield',
'Larapinta',
'Laravale',
'Lark Hill',
'Lawnton',
'Leichhardt',
'Limestone Ridges',
'Linville',
'Lockrose',
'Lockyer Waters',
'Logan Central',
'Logan Reserve',
'Logan Village',
'Loganholme',
'Loganlea',
'Lota',
'Lower Cressbrook',
'Lower Mount Walker',
'Lowood',
'Lutwyche',
'Lyons',
'Lytton',
'Macgregor',
'Mackenzie',
'Macleay Island',
'Mango Hill',
'Manly',
'Manly West',
'Mansfield',
'Marburg',
'Margate',
'Maroon',
'Marsden',
'McDowall',
'Meadowbrook',
'Meldale',
'Merryvale',
'Middle Park',
'Milbong',
'Milford',
'Milora',
'Milton',
'Minden',
'Mitchelton',
'Moggill',
'Monsildale',
'Moodlu',
'Moogerah',
'Moombra',
'Moorang',
'Moore',
'Moores Pocket',
'Moorina',
'Moorooka',
'Morayfield',
'Moreton Bay',
'Moreton Island',
'Morningside',
'Morton Vale',
'Morwincha',
'Mount Alford',
'Mount Archer',
'Mount Barney',
'Mount Beppo',
'Mount Berryman',
'Mount Byron',
'Mount Coot-tha',
'Mount Cotton',
'Mount Crosby',
'Mount Delaney',
'Mount Edwards',
'Mount Forbes',
'Mount French',
'Mount Gipps',
'Mount Glorious',
'Mount Gravatt',
'Mount Gravatt East',
'Mount Hallen',
'Mount Kilcoy',
'Mount Lindesay',
'Mount Marrow',
'Mount Mee',
'Mount Mort',
'Mount Nebo',
'Mount Ommaney',
'Mount Pleasant',
'Mount Samson',
'Mount Stanley',
'Mount Tarampa',
'Mount Walker',
'Mount Walker West',
'Mount Warren Park',
'Muirlea',
'Mulgowie',
'Munbilla',
'Mundoolun',
'Munruben',
'Murarrie',
'Murrumba',
'Murrumba Downs',
'Mutdapilly',
'Narangba',
'Nathan',
'Neurum',
'New Beith',
'New Chum',
'New Farm',
'Newmarket',
'Newport',
'Newstead',
'Newtown',
'Nindooinbah',
'Ningi',
'Norman Park',
'North Booval',
'North Ipswich',
'North Lakes',
'North Maclean',
'North Stradbroke Island',
'North Tivoli',
'Northgate',
'Nudgee',
'Nudgee Beach',
'Nundah',
'Oaky Creek',
'Obum Obum',
'Ocean View',
'One Mile',
'Ormiston',
'Ottaba',
'Oxley',
'Paddington',
'Palen Creek',
'Pallara',
'Park Ridge',
'Park Ridge South',
'Parkinson',
'Patrick Estate',
'Peak Crossing',
'Peel Island',
'Petrie',
'Petrie Terrace',
'Pine Mountain',
'Pinjarra Hills',
'Pinkenba',
'Plainland',
'Point Lookout',
'Port Of Brisbane',
'Prenzlau',
'Priestdale',
'Pullenvale',
'Purga',
'Raceview',
'Radford',
'Ransome',
'Rathdowney',
'Red Hill',
'Redbank',
'Redbank Creek',
'Redbank Plains',
'Redcliffe',
'Redland Bay',
'Regency Downs',
'Regents Park',
'Richlands',
'Rifle Range',
'Ripley',
'Riverhills',
'Riverview',
'Roadvale',
'Robertson',
'Rochedale',
'Rochedale South',
'Rocklea',
'Rocksberg',
'Rosevale',
'Rosewood',
'Rothwell',
'Royston',
'Runcorn',
'Running Creek',
'Rush Creek',
'Russell Island',
'Sadliers Crossing',
'Salisbury',
'Samford Valley',
'Samford Village',
'Samsonvale',
'Sandgate',
'Sandstone Point',
'Sandy Creek',
'Scarborough',
'Scrub Creek',
'Seven Hills',
'Seventeen Mile Rocks',
'Shailer Park',
'Sheep Station Creek',
'Sheldon',
'Sherwood',
'Shorncliffe',
'Silkstone',
'Silverdale',
'Sinnamon Park',
'Slacks Creek',
'Somerset Dam',
'South Brisbane',
'South Maclean',
'South Ripley',
'Split Yard Creek',
'Spring Creek',
'Spring Hill',
'Spring Mountain',
'Springfield',
'Springfield Central',
'Springfield Lakes',
'Springwood',
'St Lucia',
'Stafford',
'Stafford Heights',
'Stanmore',
'Stockleigh',
'Stony Creek',
'Strathpine',
'Stretton',
'Summerholm',
'Sumner',
'Sunnybank',
'Sunnybank Hills',
'Swanbank',
'Tabooba',
'Tabragalba',
'Taigum',
'Tallegalla',
'Tamborine',
'Tamrookum',
'Tamrookum Creek',
'Tanah Merah',
'Tarampa',
'Taringa',
'Tarome',
'Tarragindi',
'Templin',
'Teneriffe',
'Tennyson',
'Teviotville',
'Thagoona',
'The Bluff',
'The Gap',
'Thorneside',
'Thornlands',
'Thornton',
'Tingalpa',
'Tivoli',
'Toogoolawah',
'Toorbul',
'Toowong',
'Townson',
'Underwood',
'Undullah',
'Upper Brookfield',
'Upper Caboolture',
'Upper Kedron',
'Upper Mount Gravatt',
'Veresdale',
'Veresdale Scrub',
'Vernor',
'Victoria Point',
'Villeneuve',
'Virginia',
'Wacol',
'Wakerley',
'Wallaces Creek',
'Walloon',
'Wamuran',
'Wamuran Basin',
'Wanora',
'Warner',
'Warrill View',
'Washpool',
'Waterford',
'Waterford West',
'Wavell Heights',
'Wellington Point',
'Welsby',
'West End',
'West Ipswich',
'Westlake',
'Westvale',
'White Patch',
'White Rock',
'Whiteside',
'Wights Mountain',
'Willawong',
'Willowbank',
'Wilsons Plains',
'Wilston',
'Windaroo',
'Windsor',
'Winya',
'Wishart',
'Wivenhoe Hill',
'Wivenhoe Pocket',
'Wolffdene',
'Woodend',
'Woodford',
'Woodhill',
'Woodridge',
'Woody Point',
'Woolloongabba',
'Woolmar',
'Woolooman',
'Wooloowin',
'Woolshed',
'Woorim',
'Wulkuraka',
'Wyaralong',
'Wynnum',
'Wynnum West',
'Yamanto',
'Yarrabilba',
'Yeerongpilly',
'Yeronga',
'Yimbun',
'Yugar',
'Zillmere',
)

Adelaide_suburbs = (

'Aberfoyle Park',
'Adelaide',
'Adelaide Airport',
'Albert Park',
'Alberton',
'Aldgate',
'Aldinga',
'Aldinga Beach',
'Allenby Gardens',
'Andrews Farm',
'Angle Park',
'Angle Vale',
'Ascot Park',
'Ashford',
'Ashton',
'Athelstone',
'Athol Park',
'Auldana',
'Balhannah',
'Banksia Park',
'Basket Range',
'Beaumont',
'Bedford Park',
'Belair',
'Bellevue Heights',
'Beulah Park',
'Beverley',
'Bibaringa',
'Biggs Flat',
'Birdwood',
'Birkenhead',
'Black Forest',
'Blackwood',
'Blair Athol',
'Blakeview',
'Blakiston',
'Blewitt Springs',
'Bolivar',
'Bowden',
'Bradbury',
'Brahma Lodge',
'Bridgewater',
'Brighton',
'Broadview',
'Brompton',
'Brooklyn Park',
'Brown Hill Creek',
'Brukunga',
'Buchfelde',
'Buckland Park',
'Bugle Ranges',
'Burnside',
'Burton',
'Callington',
'Camden Park',
'Campbelltown',
'Carey Gully',
'Castambul',
'Cavan',
'Chain Of Ponds',
'Chandlers Hill',
'Chapel Hill',
'Charleston',
'Cheltenham',
'Cherry Gardens',
'Cherryville',
'Christie Downs',
'Christies Beach',
'Clapham',
'Clarence Gardens',
'Clarence Park',
'Clarendon',
'Clearview',
'Cleland',
'Clovelly Park',
'College Park',
'Collinswood',
'Colonel Light Gardens',
'Concordia',
'Coromandel East',
'Coromandel Valley',
'Cowandilla',
'Crafers',
'Crafers West',
'Craigburn Farm',
'Craigmore',
'Cromer',
'Croydon',
'Croydon Park',
'Cudlee Creek',
'Cumberland Park',
'Darlington',
'Davoren Park',
'Daw Park',
'Dawesley',
'Dernancourt',
'Devon Park',
'Direk',
'Dorset Vale',
'Dover Gardens',
'Dry Creek',
'Dudley Park',
'Dulwich',
'Eastwood',
'Echunga',
'Eden Hills',
'Edinburgh',
'Edinburgh North',
'Edwardstown',
'Elizabeth',
'Elizabeth Downs',
'Elizabeth East',
'Elizabeth Grove',
'Elizabeth North',
'Elizabeth Park',
'Elizabeth South',
'Elizabeth Vale',
'Enfield',
'Erindale',
'Ethelton',
'Evandale',
'Evanston',
'Evanston Gardens',
'Evanston Park',
'Evanston South',
'Everard Park',
'Exeter',
'Fairview Park',
'Felixstow',
'Ferryden Park',
'Findon',
'Firle',
'Fitzroy',
'Flagstaff Hill',
'Flaxley',
'Flinders Park',
'Forest Range',
'Forestville',
'Forreston',
'Frewville',
'Fulham',
'Fulham Gardens',
'Fullarton',
'Garden Island',
'Gawler',
'Gawler Belt',
'Gawler East',
'Gawler River',
'Gawler South',
'Gawler West',
'Gepps Cross',
'Gilberton',
'Gilles Plains',
'Gillman',
'Glandore',
'Glanville',
'Glen Osmond',
'Glenalta',
'Glenelg',
'Glenelg East',
'Glenelg North',
'Glenelg South',
'Glengowrie',
'Glenside',
'Glenunga',
'Globe Derby Park',
'Glynde',
'Golden Grove',
'Goodwood',
'Gould Creek',
'Grange',
'Green Fields',
'Green Hills Range',
'Greenacres',
'Greenhill',
'Greenwith',
'Gulfview Heights',
'Gumeracha',
'Hackham',
'Hackham West',
'Hackney',
'Hahndorf',
'Hallett Cove',
'Hampstead Gardens',
'Happy Valley',
'Harrogate',
'Hawthorn',
'Hawthorndene',
'Hay Valley',
'Hazelwood Park',
'Heathfield',
'Heathpool',
'Hectorville',
'Hendon',
'Henley Beach',
'Henley Beach South',
'Hewett',
'Highbury',
'Highgate',
'Hillbank',
'Hillcrest',
'Hillier',
'Hilton',
'Hindmarsh',
'Holden Hill',
'Hope Valley',
'Horsnell Gully',
'Houghton',
'Hove',
'Humbug Scrub',
'Huntfield Heights',
'Hyde Park',
'Ingle Farm',
'Inglewood',
'Ironbank',
'Joslin',
'Jupiter Creek',
'Kalbeeba',
'Kangarilla',
'Kangaroo Flat',
'Kanmantoo',
'Kensington',
'Kensington Gardens',
'Kensington Park',
'Kent Town',
'Kenton Valley',
'Kersbrook',
'Keswick',
'Keswick Terminal',
'Kidman Park',
'Kilburn',
'Kilkenny',
'Kings Park',
'Kingsford',
'Kingston Park',
'Kingswood',
'Klemzig',
'Kudla',
'Kuitpo',
'Kurralta Park',
'Largs Bay',
'Largs North',
'Leabrook',
'Leawood Gardens',
'Lenswood',
'Lewiston',
'Linden Park',
'Littlehampton',
'Lobethal',
'Lockleys',
'Longwood',
'Lonsdale',
'Lower Hermitage',
'Lower Mitcham',
'Lynton',
'Macdonald Park',
'Magill',
'Malvern',
'Manningham',
'Mansfield Park',
'Marble Hill',
'Marden',
'Marino',
'Marion',
'Marleston',
'Marryatville',
'Maslin Beach',
'Mawson Lakes',
'Maylands',
'McLaren Flat',
'McLaren Vale',
'Meadows',
'Medindie',
'Medindie Gardens',
'Melrose Park',
'Mile End',
'Mile End South',
'Millbrook',
'Millswood',
'Mitcham',
'Mitchell Park',
'Moana',
'Modbury',
'Modbury Heights',
'Modbury North',
'Montacute',
'Morphett Vale',
'Morphettville',
'Mount Barker',
'Mount Barker Junction',
'Mount Barker Springs',
'Mount Barker Summit',
'Mount Crawford',
'Mount George',
'Mount Osmond',
'Mount Torrens',
'Munno Para',
'Munno Para Downs',
'Munno Para West',
'Mylor',
'Myrtle Bank',
'Nailsworth',
'Nairne',
'Netherby',
'Netley',
'New Port',
'Newton',
'Noarlunga Centre',
'Noarlunga Downs',
'North Adelaide',
'North Brighton',
'North Haven',
'North Plympton',
'Northfield',
'Northgate',
'Norton Summit',
'Norwood',
'Novar Gardens',
'Oakbank',
'Oakden',
'Oaklands Park',
'Old Noarlunga',
'Old Reynella',
'One Tree Hill',
'Onkaparinga Hills',
'Osborne',
'Ottoway',
'Outer Harbor',
'Ovingham',
'Paechtown',
'Panorama',
'Para Hills',
'Para Hills West',
'Para Vista',
'Paracombe',
'Paradise',
'Parafield',
'Parafield Gardens',
'Paralowie',
'Park Holme',
'Parkside',
'Pasadena',
'Payneham',
'Payneham South',
'Penfield',
'Penfield Gardens',
'Pennington',
'Peterhead',
'Petwood',
'Piccadilly',
'Plympton',
'Plympton Park',
'Pooraka',
'Port Adelaide',
'Port Noarlunga',
'Port Noarlunga South',
'Port Willunga',
'Prospect',
'Queenstown',
'Redwood Park',
'Regency Park',
'Reid',
'Renown Park',
'Reynella',
'Reynella East',
'Richmond',
'Ridgehaven',
'Ridleyton',
'Rose Park',
'Rosewater',
'Roseworthy',
'Rosslyn Park',
'Rostrevor',
'Royal Park',
'Royston Park',
'Salisbury',
'Salisbury Downs',
'Salisbury East',
'Salisbury Heights',
'Salisbury North',
'Salisbury Park',
'Salisbury Plain',
'Salisbury South',
'Sampson Flat',
'Scott Creek',
'Seacliff',
'Seacliff Park',
'Seacombe Gardens',
'Seacombe Heights',
'Seaford',
'Seaford Heights',
'Seaford Meadows',
'Seaford Rise',
'Seaton',
'Seaview Downs',
'Sefton Park',
'Sellicks Beach',
'Sellicks Hill',
'Semaphore',
'Semaphore Park',
'Semaphore South',
'Sheidow Park',
'Skye',
'Smithfield',
'Smithfield Plains',
'Somerton Park',
'South Brighton',
'South Plympton',
'Springfield',
'St Agnes',
'St Clair',
'St Georges',
'St Ives',
'St Kilda',
'St Marys',
'St Morris',
'St Peters',
'Stepney',
'Stirling',
'Stonyfell',
'Sturt',
'Summertown',
'Surrey Downs',
'Taperoo',
'Tatachilla',
'Tea Tree Gully',
'Tennyson',
'Teringie',
'Thebarton',
'Thorngate',
'Toorak Gardens',
'Torrens Island',
'Torrens Park',
'Torrensville',
'Totness',
'Tranmere',
'Trinity Gardens',
'Trott Park',
'Tusmore',
'Two Wells',
'Uleybury',
'Underdale',
'Unley',
'Unley Park',
'Upper Hermitage',
'Upper Sturt',
'Uraidla',
'Urrbrae',
'Vale Park',
'Valley View',
'Verdun',
'Virginia',
'Vista',
'Walkerville',
'Walkley Heights',
'Ward Belt',
'Warradale',
'Waterfall Gully',
'Waterloo Corner',
'Wattle Park',
'Wayville',
'Welland',
'West Beach',
'West Croydon',
'West Hindmarsh',
'West Lakes',
'West Lakes Shore',
'West Richmond',
'Westbourne Park',
'Whites Valley',
'Willaston',
'Willunga',
'Willunga South',
'Windsor Gardens',
'Wingfield',
'Wistow',
'Woodcroft',
'Woodforde',
'Woodside',
'Woodville',
'Woodville Gardens',
'Woodville North',
'Woodville Park',
'Woodville South',
'Woodville West',
'Wynn Vale',
'Yatala Vale',
'Yattalunga',

)

Perth_suburbs = (
'Alexander Heights',
'Alfred Cove',
'Alkimos',
'Anketell',
'Applecross',
'Ardross',
'Armadale',
'Ascot',
'Ashby',
'Ashendon',
'Ashfield',
'Attadale',
'Atwell',
'Aubin Grove',
'Aveley',
'Avon Valley National Park',
'Bailup',
'Balcatta',
'Baldivis',
'Balga',
'Ballajura',
'Banjup',
'Banksia Grove',
'Barragup',
'Baskerville',
'Bassendean',
'Bateman',
'Bayswater',
'Beaconsfield',
'Beckenham',
'Bedford',
'Bedfordale',
'Beechboro',
'Beechina',
'Beeliar',
'Beldon',
'Belhus',
'Bellevue',
'Belmont',
'Bennett Springs',
'Bentley',
'Bertram',
'Bibra Lake',
'Bickley',
'Bicton',
'Birchmont',
'Blythewood',
'Booragoon',
'Bouvard',
'Boya',
'Brabham',
'Brentwood',
'Brigadoon',
'Brookdale',
'Bull Creek',
'Bullsbrook',
'Burns Beach',
'Burswood',
'Butler',
'Byford',
'Calista',
'Camillo',
'Canning Mills',
'Canning Vale',
'Cannington',
'Carabooda',
'Cardup',
'Carine',
'Carlisle',
'Carmel',
'Carramar',
'Casuarina',
'Caversham',
'Champion Lakes',
'Chidlow',
'Churchlands',
'City Beach',
'Claremont',
'Clarkson',
'Clifton',
'Cloverdale',
'Cockburn Central',
'Como',
'Connolly',
'Coodanup',
'Coogee',
'Coolbellup',
'Coolbinia',
'Cooloongup',
'Coolup',
'Cottesloe',
'Craigie',
'Crawley',
'Cullacabardee',
'Currambine',
'Daglish',
'Dalkeith',
'Darch',
'Darling Downs',
'Darlington',
'Dawesville',
'Dayton',
'Dianella',
'Doubleview',
'Dudley Park',
'Duncraig',
'East Cannington',
'East Fremantle',
'East Perth',
'East Rockingham',
'East Victoria Park',
'Eden Hill',
'Edgewater',
'Eglinton',
'Ellenbrook',
'Embleton',
'Erskine',
'Fairbridge',
'Falcon',
'Ferndale',
'Floreat',
'Forrestdale',
'Forrestfield',
'Fremantle',
'Furnissdale',
'Garden Island',
'Gidgegannup',
'Girrawheen',
'Glen Forrest',
'Glendalough',
'Gnangara',
'Golden Bay',
'Gooseberry Hill',
'Gorrie',
'Gosnells',
'Greenfields',
'Greenmount',
'Greenwood',
'Guildford',
'Gwelup',
'Hacketts Gully',
'Halls Head',
'Hamersley',
'Hamilton Hill',
'Hammond Park',
'Harrisdale',
'Haynes',
'Hazelmere',
'Heathridge',
'Helena Valley',
'Henderson',
'Henley Brook',
'Herdsman',
'Herne Hill',
'Herron',
'High Wycombe',
'Highgate',
'Hilbert',
'Hillarys',
'Hillman',
'Hilton',
'Hocking',
'Hope Valley',
'Hopeland',
'Hovea',
'Huntingdale',
'Iluka',
'Inglewood',
'Innaloo',
'Jandabup',
'Jandakot',
'Jane Brook',
'Jarrahdale',
'Jindalee',
'Jolimont',
'Joondalup',
'Joondanna',
'Kalamunda',
'Kallaroo',
'Karawara',
'Kardinya',
'Karnup',
'Karragullen',
'Karrakatta',
'Karrakup',
'Karrinyup',
'Kelmscott',
'Kensington',
'Kenwick',
'Keralup',
'Kewdale',
'Keysbrook',
'Kiara',
'Kings Park',
'Kingsley',
'Kinross',
'Koondoola',
'Koongamia',
'Kwinana Beach',
'Kwinana Town Centre',
'Lakelands',
'Landsdale',
'Langford',
'Lathlain',
'Leda',
'Leederville',
'Leeming',
'Lesley',
'Lesmurdie',
'Lexia',
'Lockridge',
'Lynwood',
'Maddington',
'Madeley',
'Madora Bay',
'Mahogany Creek',
'Maida Vale',
'Malaga',
'Malmalling',
'Mandogalup',
'Mandurah',
'Manning',
'Marangaroo',
'Mardella',
'Mariginiup',
'Marmion',
'Martin',
'Maylands',
'Meadow Springs',
'Medina',
'Meelon',
'Melaleuca',
'Melville',
'Menora',
'Merriwa',
'Middle Swan',
'Midland',
'Midvale',
'Millendon',
'Mindarie',
'Mirrabooka',
'Morley',
'Mosman Park',
'Mount Claremont',
'Mount Hawthorn',
'Mount Helena',
'Mount Lawley',
'Mount Nasura',
'Mount Pleasant',
'Mount Richon',
'Mullaloo',
'Mundaring',
'Mundijong',
'Munster',
'Murdoch',
'Myaree',
'Nambeelup',
'Naval Base',
'Nedlands',
'Neerabup',
'Nirimba',
'Nollamara',
'Noranda',
'North Beach',
'North Coogee',
'North Dandalup',
'North Fremantle',
'North Lake',
'North Perth',
'North Yunderup',
'Northbridge',
'Nowergup',
'Oakford',
'Ocean Reef',
'Oldbury',
'Orange Grove',
'Orelia',
'Osborne Park',
'Padbury',
'Palmyra',
'Parkerville',
'Parklands',
'Parkwood',
'Parmelia',
'Paulls Valley',
'Pearsall',
'Peppermint Grove',
'Peron',
'Perth',
'Perth Airport',
'Piara Waters',
'Pickering Brook',
'Piesse Brook',
'Pinjar',
'Pinjarra',
'Point Grey',
'Port Kennedy',
'Postans',
'Queens Park',
'Quinns Rocks',
'Ravenswood',
'Red Hill',
'Redcliffe',
'Reservoir',
'Ridgewood',
'Riverton',
'Rivervale',
'Rockingham',
'Roleystone',
'Rossmoyne',
'Rottnest Island',
'Safety Bay',
'Salter Point',
'Samson',
'San Remo',
'Sawyers Valley',
'Scarborough',
'Secret Harbour',
'Serpentine',
'Seville Grove',
'Shelley',
'Shenton Park',
'Shoalwater',
'Silver Sands',
'Sinagra',
'Singleton',
'Sorrento',
'South Fremantle',
'South Guildford',
'South Lake',
'South Perth',
'South Yunderup',
'Southern River',
'Spearwood',
'St James',
'Stake Hill',
'Stirling',
'Stoneville',
'Stratton',
'Subiaco',
'Success',
'Swan View',
'Swanbourne',
'Tamala Park',
'Tapping',
'The Lakes',
'The Spectacles',
'The Vines',
'Thornlie',
'Trigg',
'Tuart Hill',
'Two Rocks',
'Upper Swan',
'Victoria Park',
'Viveash',
'Waikiki',
'Walliston',
'Walyunga National Park',
'Wandi',
'Wangara',
'Wannanup',
'Wanneroo',
'Warnbro',
'Warwick',
'Waterford',
'Watermans Bay',
'Wattle Grove',
'Wattleup',
'Wellard',
'Welshpool',
'Wembley',
'Wembley Downs',
'West Coolup',
'West Leederville',
'West Perth',
'West Pinjarra',
'West Swan',
'Westminster',
'Whitby',
'White Gum Valley',
'Whiteman',
'Willagee',
'Willetton',
'Wilson',
'Winthrop',
'Woodbridge',
'Woodlands',
'Woodvale',
'Wooroloo',
'Wungong',
'Yanchep',
'Yangebup',
'Yokine', 
)